export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "kishore",
			profileImg: "/avatars/boy1.png",
			fullName: "Kishore Prasad",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "babu",
					profileImg: "/avatars/boy2.png",
					fullName: "R Babu",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "kishore",
			profileImg: "/avatars/boy2.png",
			fullName: "Kishore Prasad",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "babu",
					profileImg: "/avatars/boy3.png",
					fullName: "R Babu",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "johndoe",
			profileImg: "/avatars/boy3.png",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "johndoe",
			profileImg: "/avatars/boy3.png",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "/avatars/girl3.png",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "Kishore Prasad",
		username: "kishore",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "Vijay",
		username: "thalapathy",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "R Babu",
		username: "babu",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "4",
		fullName: "M Ilakkiyan",
		username: "ilakki",
		profileImg: "/avatars/boy3.png",
	},
];